services:
  router:
    build:
      context: ..
      dockerfile: dev/Dockerfile
    ports:
      - "8000:8000"
    environment:
      DEBUG: "false"
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: eu-central-1
      CELERY__APP_NAME: debugmate
      CELERY__TASK_NAME: debugmate.debug_endpoint
      CELERY__BROKER_URL: sqs://test:test@localstack:4566
      CELERY__ENDPOINT_URL: http://localstack:4566
      CELERY__IS_SECURE: "false"
      CELERY__REGION: eu-central-1
      CELERY__VISIBILITY_TIMEOUT: "3600"
      CELERY__POLLING_INTERVAL: "5"
      CELERY__QUEUE_NAME: debugmate-tasks
    depends_on:
      localstack:
        condition: service_healthy

  debug-worker:
    build:
      context: ..
      dockerfile: dev/worker/Dockerfile
    environment:
      DEBUG: "false"
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: eu-central-1
      CELERY__APP_NAME: debugmate
      CELERY__TASK_NAME: debugmate.debug_endpoint
      CELERY__BROKER_URL: sqs://test:test@localstack:4566
      CELERY__ENDPOINT_URL: http://localstack:4566
      CELERY__IS_SECURE: "false"
      CELERY__REGION: eu-central-1
      CELERY__VISIBILITY_TIMEOUT: "3600"
      CELERY__POLLING_INTERVAL: "5"
      CELERY__QUEUE_NAME: debugmate-tasks
    depends_on:
      localstack:
        condition: service_healthy

  localstack:
    image: localstack/localstack:3.8.1
    ports:
      - "4566:4566"
    environment:
      SERVICES: sqs
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_DEFAULT_REGION: eu-central-1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 5s
      retries: 20
